// <auto-generated />
namespace IMS.MonitorDbContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddDepartmentType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDepartmentType));
        
        string IMigrationMetadata.Id
        {
            get { return "201604100059293_AddDepartmentType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
