// <auto-generated />
namespace IMS.ImsDbContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ReWriteIndicatorAlgorithm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReWriteIndicatorAlgorithm));
        
        string IMigrationMetadata.Id
        {
            get { return "201604151508520_ReWriteIndicatorAlgorithm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
